version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: rangepos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: posdb
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: change_me_local_only
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
